### ISSUE TITLE
not sufficiently robust to FB API failures

### ISSUE THREAD

**Issue by fazalmajid** [fazalmajid/temboz#103]
```
########## BEGIN ############################################################
```

   <class 'urllib2.URLError'>: <urlopen error The read operation timed out>Traceback (most recent call last):  File "/home/majid/temboz/update.py", line 330, in run    social.fb_post(fb_token, callout + title, url)
     File "/home/majid/temboz/social.py", line 11, in fb_post    '&link=' + urllib2.quote(url)).read()  File "/usr/local/lib/python2.7/urllib2.py", line 126, in urlopen
       return _opener.open(url, data, timeout)  File "/usr/local/lib/python2.7/urllib2.py", line 392, in open    response = self._open(req, data)  File "/usr/local/lib/python2.7/urllib2.py", line 410, in _open
       '_open', req)  File "/usr/local/lib/python2.7/urllib2.py", line 370, in _call_chain    result = func(*args)
     File "/usr/local/lib/python2.7/urllib2.py", line 1194, in https_open    return self.do_open(httplib.HTTPSConnection, req)
     File "/usr/local/lib/python2.7/urllib2.py", line 1161, in do_open
       raise URLError(err)
   URLError: <urlopen error The read operation timed out>
   ---------- local variables: --------------------------------------------------
   self : <urllib2.HTTPSHandler instance at 0x894524c>
   req : <urllib2.Request instance at 0x874642c>
   ########## END ###############################################################

**Comment by fazalmajid** [comment]
WONTFIX as FB’s post Cambridge Analytica changes mean it’s no longer usable. I’ll have to write to another API like IFTTT instead
