### ISSUE TITLE
temboz initialisation crash

### ISSUE THREAD

**Issue by gil-andre** [fazalmajid/temboz#119]
Installing a brand new temboz on a Slackware 14.1 machine:

Everything works fine, following the instructions in the README file, until: 

```
Enter password:
Confirm password:
WARNING: rebuilding mv_feed_stats...Traceback (most recent call last):
  File "./bin/temboz", line 23, in <module>
    tembozapp.bootstrap.do_bootstrap()
  File "/home/gil/kallithea/temboz_rss/lib/python2.7/site-packages/tembozapp/bootstrap.py", line 77, in do_bootstrap
    import dbop
  File "/home/gil/kallithea/temboz_rss/lib/python2.7/site-packages/tembozapp/dbop.py", line 446, in <module>
    mv_on_demand(d)
  File "/home/gil/kallithea/temboz_rss/lib/python2.7/site-packages/tembozapp/dbop.py", line 172, in mv_on_demand
    snr_mv(db, c)
  File "/home/gil/kallithea/temboz_rss/lib/python2.7/site-packages/tembozapp/dbop.py", line 93, in snr_mv
    'decay': getattr(param, 'decay', 30)
sqlite3.OperationalError: near "with": syntax error
```

SQLite3 binary is present in `/usr/bin/sqlite3`

List of packages installed by `pip`:

```
$ pip list
Package       Version
------------- ---------
argon2-cffi   18.3.0
certifi       2018.8.24
cffi          1.11.5
chardet       3.0.4
Click         7.0
enum34        1.1.6
Flask         1.0.2
html5lib      1.0.1
idna          2.7
itsdangerous  0.24
Jinja2        2.10
MarkupSafe    1.0
passlib       1.7.1
pip           18.1
pycparser     2.19
requests      2.19.1
setuptools    40.4.3
six           1.11.0
temboz        2.3.1
translitcodec 0.4.0
urllib3       1.23
webencodings  0.5.1
Werkzeug      0.14.1
wheel         0.32.1
yappi         0.98
```

Am I missing something? Many thanks in advance!

**Comment by gil-andre** [comment]
Crash issue is consistent, since deleting the entire virtual environment and re-creating produces the exact same crash, backtrace response at the same installation point.

**Comment by fazalmajid** [comment]
What version of SQLite do you have? WITH statements (common table expressions) were introduced with 3.8.3 in 2014.
```
mordac ~>sqlite3 --version
3.25.0 2018-09-15 04:01:47 b63af6c3bd33152742648d5d2e8dc5d5fcbcdd27df409272b6aea00a6f761760
```

**Comment by gil-andre** [comment]
Closing the issue. Sorry for the noise!
